# Generated by Django 4.1.5 on 2023-01-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Tag")),
                ("start", models.TimeField(verbose_name="Start")),
                ("end", models.TimeField(verbose_name="Ende")),
            ],
        ),
    ]
