# Generated by Django 4.1.5 on 2023-01-18 04:21

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("times", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="times.unit"
            ),
        ),
    ]
