# Generated by Django 4.1.5 on 2023-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_unit_plan_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Pläne'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Einheit', 'verbose_name_plural': 'Einheiten'},
        ),
        migrations.AddField(
            model_name='plan',
            name='end_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='times.unit', verbose_name='Einheit'),
        ),
    ]
